import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({style: 'normal', weight: '400', preload: false, display: 'swap', serif: false})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/images/logoLS-no-bg.svg" type="image/x-icon" />
        <title>Gasify</title>
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
