import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({style: 'normal', weight: '400', preload: false, display: 'swap', serif: false})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
